FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY . .

RUN chmod +x mvnw

RUN ./mvnw clean package -DskipTests

EXPOSE 80

CMD ["sh", "-c", "java -jar target/user-management-system-0.0.1-SNAPSHOT.jar --server.port=${PORT:-80}"]