spring.application.name=user-management-system

server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:usermanagement
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.defer-datasource-initialization=true

app.jwt.secret=ThisIsMyVerySecureJwtSecretKeyForUserManagementSystem2026
app.jwt.expiration=86400000